### ISSUE TITLE
[Feature Request] Prepopulate input with "things-at-point" for symbol?

### ISSUE THREAD

**Issue by dunkarooftop** [xuchunyang/dash-alfred.el#1]
Is it possible to add a feature like in "swiper". It will prepopulate the word/symbol under the cursor when trigger 'dash-alfred-ivy' ? :)

Thank you

**Comment by xuchunyang** [comment]
It should be fixed. I also decided to fill the docset name. Feel free to give feedback. And if you just want to tweak it in your own init file, you can advice the function `dash-alfred-guess-input`.

**Comment by dunkarooftop** [comment]
works great, Thanks :)
